app/src/assets/styles/globals.css
app/src/views/DesignSystem/TypographyPage.tsx

added component typographyPage

---

app/src/App.tsx
app/src/services/firebase/firestore.ts
app/src/views/CompanyInfo/CompanyInfoForm.tsx
app/src/views/CompanyInfo/CompanyInfoPage.tsx
app/src/views/UserInfo/constants.ts
app/src/views/UserInfo/userInfoForm.tsx
functions/src/triggers/user.ts
package-lock.json
typescript-types/db.types.ts

Company info

---

functions/example.runtimeconfig.json
functions/src/email/sendEmail.ts

Use new email address for dev environment

Fix email config

---

app/public/index.html
app/src/assets/styles/globals.css
app/src/components/ErrorPage/style.ts

Add new font for errors code
On the error page, for error code add font 'Press Start 2P' after the design update

Update style error pages

---

app/src/components/AuthForms/SignIn/SignIn.tsx
app/src/components/DevButton/DevButton.tsx
app/src/utils/url.utils.ts

Не работала наша магическая дев кнопка.
Поправил пароли и гет параметры

FixDevButton

---

README.md
typescript-types/database-structure.txt

To visualize test file with database constructor use https://flowchart.fun/

add database structure

---

functions/src/email/invite.ts
functions/src/email/sendEmail.ts
functions/src/email/templates/confirmCompany.ts
functions/src/email/templates/templateConfig.ts

Create template for sending confirm company email

---

app/package-lock.json
app/package.json
app/src/components/AuthForms/SetPassword.tsx
app/src/components/AuthForms/SignIn/SelectDomain.tsx
app/src/components/AuthForms/SignIn/SignIn.tsx
app/src/components/Forms/SignInForm.tsx
app/src/services/firebase/errorMessages.ts
app/src/utils/formValidator.ts

Add hookFormResolver, add shemaValidation, add hook form in SignIn

Add validation form

---

.github/workflows/chromatic-merge.yml
.github/workflows/chromatic-pull-request.yml
.github/workflows/firebase-merge.yml
.github/workflows/firebase-pull-request.yml
.github/workflows/lint-merge.yml
.github/workflows/lint-pull-request.yml
README.md
app/src/components/AuthForms/ConfirmCompany.tsx
app/src/components/AuthForms/CreateCompany/CreateCompany.tsx
functions/src/callable/company/confirmCompany.ts
functions/src/callable/company/registerCompany.ts
functions/src/callable/devTools.ts
functions/src/callable/invite/acceptInvite.ts
functions/src/callable/invite/inviteUser.ts
functions/src/callable/user/setPassword.ts
functions/src/dbAdmin/createCompanyDatabaseStructure.ts
functions/src/dbAdmin/createUserInvitation.ts
functions/src/dbAdmin/initResetUserRequestInDatabase.ts
functions/src/dbAdmin/registerCompanyInDatabase.ts
functions/src/email/invite.ts
functions/src/email/templates/confirmCompany.ts
functions/src/spreadsheet/getBackOfficeDocument.ts
functions/src/utils/time.ts
typescript-types/database-structure.txt
typescript-types/db.types.ts
typescript-types/package-lock.json
typescript-types/package.json

Ограничение времени жизни ссылки при регистрации
Добавил поле createdAt - время создания дока с верификацией. Это поле чисто для истории
Добавил поле expiredAt - это время когда ссылка перестанет быть рабочей
с expiredAt можно гибко настраивать приглажения.
Например. 
- при регистрации компании через наш сайт.  Время жизни ссылки должно быть 10 минут. (для компании, приглашения в компанию и установки пароля)
- при приглашении юзера в компанию  Время жизни ссылки должно быть 30 дней. (приглашения в компанию и установки пароля)
- при регистрации компании через бэк офисс.  Время жизни ссылки должно быть 30 дней. (для компании, приглашения в компанию и установки пароля)
---

Expired time for sign up

---

app/src/components/AuthForms/CreateCompany/CreateCompany.tsx
app/src/components/AuthForms/CreateCompany/TermsAcceptControl.tsx

Обновил генерацию доменых имен при резигстрации.
Сделал их более человечными.
Сейчас для генерации будут использоваться емаил и рандомные цифры.
Из эмайла берется часть которая до @ и вытягиваются буквы. т.е. все точки тире удаляются.
Вторая часть домена цифры.. 
Потому-что из буквы получается какие-то не очень красивые слова. цифры более нейтральные
---
Ещё добавил бэкдор, что-бы можно было из формы самому писать доменные имена
---
---

Impove name of domain

---

functions/src/callable/devTools.ts
functions/src/dbAdmin/fillDepartmentsWithRandomUsers.ts
functions/src/dbAdmin/insertDepartmentIntoCompany.ts
typescript-types/database-structure.txt
typescript-types/db.types.ts

Обновление структуры бд
Добавлена коллекция departments с полями
name - наименование департамента
headId - uid пользователя, руководителя департамента
В коллекцию users добавлено поле departmentID (uid департамента, к которому относится пользователь)
Добавлен интерфейс DepartmentInfo
Обновлен интерфейс UserInfo
Добавлена функция генерации департаментов generateDepartments
Добавлена функция fillDepartmentsWithRandomUsers  для заполнения departmentID в коллекции users и заполнения headId в коллекции departments
---
Готовый ПР с обновленной структурой бд и генерацией тестовых департаментов, исправлены комментарии пр #160 
---
Пару скриншотов помогут легче вникнуть в проект и код ревью пройдет быстрее
---
- [+] database-structure.txt актуальный

Update db structure

---

typescript-types/package-lock.json
typescript-types/package.json
typescript-types/tsconfig.json

Фикс деплоя
tsconfig
add package firebase/utils

[Bug]fix Firebase on merge

---

.github/workflows/firebase-merge.yml

В общих чертах описать пулл реквест (2-3 предложения)
Я делаю такую-то фичу вот такие вот экраны.
Описать это готовая фича или подготовка или рефакторинг.
---
Может быть это драфтовый пулл реквест, что бы понять правильное ли направлении.
Например "Сделал пример стилизации компонента, не уверен что в правильном направлении иду, гляньте плез. Нужен общий ревью. не влезая в детали"
то в этом блоке стоит описать это. Что не нужно придираться к мелочам, что пока норм если есть логи и коментарии.
Если это готовый пулл реквест, то это тоже лучше описать тут.
"ПР полностью готов к финальному ревью. Нужно проверить всё"
---
Пару скриншотов помогут легче вникнуть в проект и код ревью пройдет быстрее
---

Fix lint for deploy

---

functions/src/callable/company/registerCompany.ts
functions/src/dbAdmin/createCompanyDatabaseStructure.ts
typescript-types/db.types.ts

Создание коллекции департаментов при подтверждении компании

[Company Structure]create department on confirm company

---

app/src/components/Autocompletes/AutocompleteDepartments.tsx
app/src/components/Forms/UserCorporateInfoForm.tsx
app/src/hooks/useUsers.ts
app/src/services/firebase/firestore.ts
app/src/utils/constructUsersForTable.ts
app/src/utils/requests/updateUserCorporateInfo.ts
app/src/views/Users/ColumnForUsersTable.tsx
app/src/views/Users/UsersPage.tsx
app/src/views/UsersPages/UserRouter.tsx

add change user corporate info, fix autocomplete department, update useUsers hook
add change user corporate info - теперь можно изменять корпоративные данные пользователя
update useUsers hook - добавил метод update, с помощью которого данные в UsersTable обновляются синхронно с обновлением бд через кнопки таблицы
fix autocomplete department - добавил возможность иметь дефолтные значения, так же зафиксил баг с опциями
---
Пр готов к пушу, проверять все
слудующим пр'ом хочу обновить хук useUsers, сделать его более читаемым, разбить на подхуки

[Company Structure] add change user corporate info, fix autocomplete department, update useUsers hook

---

package-lock.json
package.json

#142 
Сделал одну команду для запуска среды разработчика.
Теперь в корневом каталоге можно запустить npm run dev (вместо /app > npm start и /functions > npm run serve)

Added dev script in package.json to start developer environment

---

.github/workflows/chromatic-merge.yml
.github/workflows/chromatic-pull-request.yml
.github/workflows/firebase-merge.yml
.github/workflows/firebase-pull-request.yml
.github/workflows/lint-merge.yml
.github/workflows/lint-pull-request.yml
README.md
package.json

Добавил установку пакетов через concurrently.

Add parallel packages install in actions and change readme(#141)

---

app/src/App.tsx
app/src/components/Header/designSystemLinks.ts
app/src/stories/SnackbarPage.stories.tsx
app/src/views/DesignSystem/index.ts

Snackbar page to storybook moved

Snackbar page to storybook

---

.github/workflows/chromatic-merge.yml
.github/workflows/chromatic-pull-request.yml
.github/workflows/firebase-merge.yml
.github/workflows/firebase-pull-request.yml
.github/workflows/lint-merge.yml
.github/workflows/lint-pull-request.yml

Fix dual installation of packages

Fix packages install

---

app/.storybook/preview.js
app/src/assets/styles/globals.css
app/src/stories/SnackbarPage.stories.tsx
functions/src/email/templates/confirmCompany.ts

Move NotificationProvider to storybook/preview

fix Snackbar page to storybook

---

app/.storybook/preview.js
app/src/App.tsx
app/src/stories/Checkbox.stories.tsx
app/src/stories/Checkboxes.stories.tsx
app/src/stories/Dialog.stories.tsx
app/src/views/DesignSystem/index.ts

Move DialogPage to storybook(#149 )

Dialog to storybook
